name: Ejecutar Script de Opciones

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta todos los días a medianoche (UTC)
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance tabulate pandas requests
      - name: Run script
        run: python analizar_opciones.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: resultados
          path: |
            resultados.txt
            todas_las_opciones.csv
            mejores_contratos.csv
